server:
  port: 9002
spring:
  kafka:
    producer:
      bootstrap-servers: 114.123.239.227:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer